<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class JuzsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('juzs')->delete();
        
        \DB::table('juzs')->insert(array (
            0 => 
            array (
                'id' => 1,
                'number' => 1,
                'from_page' => 1,
                'to_page' => 21,
                'from_aya' => 1,
                'to_aya' => 141,
                'from_sura' => 'الفاتحة',
                'to_sura' => 'البقرة',
                'from_juz' => 1,
                'alpha_num' => 11095,
                'created_at' => '2021-04-12 11:24:01',
                'updated_at' => '2021-04-12 11:24:01',
            ),
            1 => 
            array (
                'id' => 2,
                'number' => 2,
                'from_page' => 22,
                'to_page' => 41,
                'from_aya' => 142,
                'to_aya' => 252,
                'from_sura' => 'البقرة',
                'to_sura' => 'البقرة',
                'from_juz' => 2,
                'alpha_num' => 11459,
                'created_at' => '2021-04-12 11:24:02',
                'updated_at' => '2021-04-12 11:24:02',
            ),
            2 => 
            array (
                'id' => 3,
                'number' => 3,
                'from_page' => 42,
                'to_page' => 62,
                'from_aya' => 253,
                'to_aya' => 92,
                'from_sura' => 'البقرة',
                'to_sura' => 'آل عمران',
                'from_juz' => 3,
                'alpha_num' => 11279,
                'created_at' => '2021-04-12 11:24:02',
                'updated_at' => '2021-04-12 11:24:02',
            ),
            3 => 
            array (
                'id' => 4,
                'number' => 4,
                'from_page' => 62,
                'to_page' => 81,
                'from_aya' => 93,
                'to_aya' => 23,
                'from_sura' => 'آل عمران',
                'to_sura' => 'النساء',
                'from_juz' => 4,
                'alpha_num' => 11139,
                'created_at' => '2021-04-12 11:24:02',
                'updated_at' => '2021-04-12 11:24:02',
            ),
            4 => 
            array (
                'id' => 5,
                'number' => 5,
                'from_page' => 82,
                'to_page' => 101,
                'from_aya' => 24,
                'to_aya' => 147,
                'from_sura' => 'النساء',
                'to_sura' => 'النساء',
                'from_juz' => 5,
                'alpha_num' => 11423,
                'created_at' => '2021-04-12 11:24:02',
                'updated_at' => '2021-04-12 11:24:02',
            ),
            5 => 
            array (
                'id' => 6,
                'number' => 6,
                'from_page' => 102,
                'to_page' => 121,
                'from_aya' => 148,
                'to_aya' => 81,
                'from_sura' => 'النساء',
                'to_sura' => 'المائدة',
                'from_juz' => 6,
                'alpha_num' => 11204,
                'created_at' => '2021-04-12 11:24:02',
                'updated_at' => '2021-04-12 11:24:02',
            ),
            6 => 
            array (
                'id' => 7,
                'number' => 7,
                'from_page' => 121,
                'to_page' => 141,
                'from_aya' => 82,
                'to_aya' => 110,
                'from_sura' => 'المائدة',
                'to_sura' => 'الأنعام',
                'from_juz' => 7,
                'alpha_num' => 11944,
                'created_at' => '2021-04-12 11:24:02',
                'updated_at' => '2021-04-12 11:24:02',
            ),
            7 => 
            array (
                'id' => 8,
                'number' => 8,
                'from_page' => 142,
                'to_page' => 161,
                'from_aya' => 111,
                'to_aya' => 87,
                'from_sura' => 'الأنعام',
                'to_sura' => 'الأعراف',
                'from_juz' => 8,
                'alpha_num' => 11219,
                'created_at' => '2021-04-12 11:24:02',
                'updated_at' => '2021-04-12 11:24:02',
            ),
            8 => 
            array (
                'id' => 9,
                'number' => 9,
                'from_page' => 162,
                'to_page' => 181,
                'from_aya' => 88,
                'to_aya' => 40,
                'from_sura' => 'الأعراف',
                'to_sura' => 'الأنفال',
                'from_juz' => 9,
                'alpha_num' => 11110,
                'created_at' => '2021-04-12 11:24:02',
                'updated_at' => '2021-04-12 11:24:02',
            ),
            9 => 
            array (
                'id' => 10,
                'number' => 10,
                'from_page' => 182,
                'to_page' => 201,
                'from_aya' => 41,
                'to_aya' => 92,
                'from_sura' => 'الأنفال',
                'to_sura' => 'التوبه',
                'from_juz' => 10,
                'alpha_num' => 10841,
                'created_at' => '2021-04-12 11:24:02',
                'updated_at' => '2021-04-12 11:24:02',
            ),
            10 => 
            array (
                'id' => 11,
                'number' => 11,
                'from_page' => 201,
                'to_page' => 221,
                'from_aya' => 93,
                'to_aya' => 5,
                'from_sura' => 'التوبه',
                'to_sura' => 'هود',
                'from_juz' => 11,
                'alpha_num' => 11350,
                'created_at' => '2021-04-12 11:24:02',
                'updated_at' => '2021-04-12 11:24:02',
            ),
            11 => 
            array (
                'id' => 12,
                'number' => 12,
                'from_page' => 222,
                'to_page' => 241,
                'from_aya' => 6,
                'to_aya' => 52,
                'from_sura' => 'هود',
                'to_sura' => 'يوسف',
                'from_juz' => 12,
                'alpha_num' => 11323,
                'created_at' => '2021-04-12 11:24:03',
                'updated_at' => '2021-04-12 11:24:03',
            ),
            12 => 
            array (
                'id' => 13,
                'number' => 13,
                'from_page' => 242,
                'to_page' => 261,
                'from_aya' => 53,
                'to_aya' => 52,
                'from_sura' => 'يوسف',
                'to_sura' => 'ابراهيم',
                'from_juz' => 13,
                'alpha_num' => 11121,
                'created_at' => '2021-04-12 11:24:03',
                'updated_at' => '2021-04-12 11:24:03',
            ),
            13 => 
            array (
                'id' => 14,
                'number' => 14,
                'from_page' => 262,
                'to_page' => 281,
                'from_aya' => 1,
                'to_aya' => 128,
                'from_sura' => 'الحجر',
                'to_sura' => 'النحل',
                'from_juz' => 14,
                'alpha_num' => 10886,
                'created_at' => '2021-04-12 11:24:03',
                'updated_at' => '2021-04-12 11:24:03',
            ),
            14 => 
            array (
                'id' => 15,
                'number' => 15,
                'from_page' => 282,
                'to_page' => 301,
                'from_aya' => 1,
                'to_aya' => 74,
                'from_sura' => 'الإسراء',
                'to_sura' => 'الكهف',
                'from_juz' => 15,
                'alpha_num' => 11535,
                'created_at' => '2021-04-12 11:24:03',
                'updated_at' => '2021-04-12 11:24:03',
            ),
            15 => 
            array (
                'id' => 16,
                'number' => 16,
                'from_page' => 302,
                'to_page' => 321,
                'from_aya' => 75,
                'to_aya' => 135,
                'from_sura' => 'الكهف',
                'to_sura' => 'طه',
                'from_juz' => 16,
                'alpha_num' => 11384,
                'created_at' => '2021-04-12 11:24:03',
                'updated_at' => '2021-04-12 11:24:03',
            ),
            16 => 
            array (
                'id' => 17,
                'number' => 17,
                'from_page' => 322,
                'to_page' => 341,
                'from_aya' => 1,
                'to_aya' => 78,
                'from_sura' => 'الأنبياء',
                'to_sura' => 'الحج',
                'from_juz' => 17,
                'alpha_num' => 10612,
                'created_at' => '2021-04-12 11:24:03',
                'updated_at' => '2021-04-12 11:24:03',
            ),
            17 => 
            array (
                'id' => 18,
                'number' => 18,
                'from_page' => 342,
                'to_page' => 361,
                'from_aya' => 1,
                'to_aya' => 20,
                'from_sura' => 'المؤمنون',
                'to_sura' => 'الفرقان',
                'from_juz' => 18,
                'alpha_num' => 11610,
                'created_at' => '2021-04-12 11:24:03',
                'updated_at' => '2021-04-12 11:24:03',
            ),
            18 => 
            array (
                'id' => 19,
                'number' => 19,
                'from_page' => 362,
                'to_page' => 381,
                'from_aya' => 21,
                'to_aya' => 55,
                'from_sura' => 'الفرقان',
                'to_sura' => 'النمل',
                'from_juz' => 19,
                'alpha_num' => 11337,
                'created_at' => '2021-04-12 11:24:04',
                'updated_at' => '2021-04-12 11:24:04',
            ),
            19 => 
            array (
                'id' => 20,
                'number' => 20,
                'from_page' => 382,
                'to_page' => 401,
                'from_aya' => 56,
                'to_aya' => 45,
                'from_sura' => 'النمل',
                'to_sura' => 'العنكبوت',
                'from_juz' => 20,
                'alpha_num' => 10917,
                'created_at' => '2021-04-12 11:24:04',
                'updated_at' => '2021-04-12 11:24:04',
            ),
            20 => 
            array (
                'id' => 21,
                'number' => 21,
                'from_page' => 402,
                'to_page' => 421,
                'from_aya' => 46,
                'to_aya' => 30,
                'from_sura' => 'العنكبوت',
                'to_sura' => 'الأحزاب',
                'from_juz' => 21,
                'alpha_num' => 11217,
                'created_at' => '2021-04-12 11:24:04',
                'updated_at' => '2021-04-12 11:24:04',
            ),
            21 => 
            array (
                'id' => 22,
                'number' => 22,
                'from_page' => 422,
                'to_page' => 441,
                'from_aya' => 31,
                'to_aya' => 27,
                'from_sura' => 'الأحزاب',
                'to_sura' => 'يس',
                'from_juz' => 22,
                'alpha_num' => 11443,
                'created_at' => '2021-04-12 11:24:04',
                'updated_at' => '2021-04-12 11:24:04',
            ),
            22 => 
            array (
                'id' => 23,
                'number' => 23,
                'from_page' => 442,
                'to_page' => 461,
                'from_aya' => 28,
                'to_aya' => 31,
                'from_sura' => 'يس',
                'to_sura' => 'الزمر',
                'from_juz' => 23,
                'alpha_num' => 11448,
                'created_at' => '2021-04-12 11:24:04',
                'updated_at' => '2021-04-12 11:24:04',
            ),
            23 => 
            array (
                'id' => 24,
                'number' => 24,
                'from_page' => 462,
                'to_page' => 481,
                'from_aya' => 32,
                'to_aya' => 46,
                'from_sura' => 'الزمر',
                'to_sura' => 'فصلت',
                'from_juz' => 24,
                'alpha_num' => 10861,
                'created_at' => '2021-04-12 11:24:04',
                'updated_at' => '2021-04-12 11:24:04',
            ),
            24 => 
            array (
                'id' => 25,
                'number' => 25,
                'from_page' => 482,
                'to_page' => 502,
                'from_aya' => 47,
                'to_aya' => 37,
                'from_sura' => 'فصلت',
                'to_sura' => 'الجاثية',
                'from_juz' => 25,
                'alpha_num' => 11449,
                'created_at' => '2021-04-12 11:24:04',
                'updated_at' => '2021-04-12 11:24:04',
            ),
            25 => 
            array (
                'id' => 26,
                'number' => 26,
                'from_page' => 502,
                'to_page' => 521,
                'from_aya' => 1,
                'to_aya' => 30,
                'from_sura' => 'الأحقاف',
                'to_sura' => 'الذاريات',
                'from_juz' => 26,
                'alpha_num' => 11523,
                'created_at' => '2021-04-12 11:24:05',
                'updated_at' => '2021-04-12 11:24:05',
            ),
            26 => 
            array (
                'id' => 27,
                'number' => 27,
                'from_page' => 522,
                'to_page' => 541,
                'from_aya' => 31,
                'to_aya' => 29,
                'from_sura' => 'الذاريات',
                'to_sura' => 'الحديد',
                'from_juz' => 27,
                'alpha_num' => 11169,
                'created_at' => '2021-04-12 11:24:05',
                'updated_at' => '2021-04-12 11:24:05',
            ),
            27 => 
            array (
                'id' => 28,
                'number' => 28,
                'from_page' => 542,
                'to_page' => 561,
                'from_aya' => 1,
                'to_aya' => 12,
                'from_sura' => 'المجادلة',
                'to_sura' => 'التحريم',
                'from_juz' => 28,
                'alpha_num' => 11772,
                'created_at' => '2021-04-12 11:24:05',
                'updated_at' => '2021-04-12 11:24:05',
            ),
            28 => 
            array (
                'id' => 29,
                'number' => 29,
                'from_page' => 562,
                'to_page' => 581,
                'from_aya' => 1,
                'to_aya' => 50,
                'from_sura' => 'الملك',
                'to_sura' => 'المرسلات',
                'from_juz' => 29,
                'alpha_num' => 11422,
                'created_at' => '2021-04-12 11:24:05',
                'updated_at' => '2021-04-12 11:24:05',
            ),
            29 => 
            array (
                'id' => 30,
                'number' => 30,
                'from_page' => 582,
                'to_page' => 604,
                'from_aya' => 1,
                'to_aya' => 6,
                'from_sura' => 'النبإ',
                'to_sura' => 'الناس',
                'from_juz' => 30,
                'alpha_num' => 9887,
                'created_at' => '2021-04-12 11:24:05',
                'updated_at' => '2021-04-12 11:24:05',
            ),
        ));
        
        
    }
}