<?php

namespace App\Repositories\SQL;

use App\Models\Role;
use App\Models\User;
use App\Repositories\Contracts\RoleContract;
use Illuminate\Database\Eloquent\Model;

class RoleRepository extends BaseRepository implements RoleContract
{
    /**
     * RoleRepository constructor.
     * @param Role $model
     */
    public function __construct(Role $model)
    {
        parent::__construct($model);
    }

    /**
     * Check if model has relations with any other tables
     * @param Role $model
     * @return int
     */
     public function relatedData(Role $model)
     {
        return 0;
     }

     public function remove(Model $role): mixed
     {
         $users = User::all();

         foreach ($users as $user) {
             if ($user->hasRole($role->name)) {
                 return false;
             }
         }
         return parent::remove($role); // TODO: Change the autogenerated stub
     }
}
